/**
 * Slim OpenApi Introduction
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * A simple user model.
 */
export interface User { 
    readonly id?: number;
    username?: string;
    firstName?: string;
    lastName?: string;
}

